name: maybe_slow_future
description: A package addding a "slow future" detection callback.
version: 1.0.2
homepage: https://github.com/6220119/maybe_slow_future
repository: https://github.com/6220119/maybe_slow_future
issue_tracker: https://github.com/6220119/maybe_slow_future/issues
documentation: https://github.com/6220119/maybe_slow_future

environment:
  sdk: ">=2.7.0 <3.0.0"

# dependencies:
# look, ma! no dependencies!

dev_dependencies:
  test: ^1.15.4
  fake_async: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
